### ISSUE TITLE
example workspace

### ISSUE THREAD

**Issue by Pikamuchu** [pikamachu/pika-vscode-require-cartridge-resolve#23]
Add an example workspace with files for supported code definitions.

**Comment by ecRobertEngel** [comment]
Hey do you have an update for this? I am trying to get the types working but I had no success.

**Comment by Pikamuchu** [comment]
You can see a workspace example with types here 
https://github.com/pikamachu/pika-vscode-require-cartridge-resolve/tree/related-documents/test/example-workspace
But the work in this branch is not finished yet
